---
abstract: 'Lightweight module to calculate N50 statistics from a FASTA or FASTQ file'
author:
  - 'Andrea Telatin <andrea.telatin@quadram.ac.uk>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Proch-N50
provides:
  Proch::N50:
    file: lib/Proch/N50.pm
    version: '0.05'
requires:
  FASTX::Reader: '0.02'
  perl: '5.018'
resources:
  repository: https://github.com/telatin/bioinfo.git
version: '0.05'
x_generated_by_perl: v5.22.1
x_serialization_backend: 'YAML::Tiny version 1.70'
