# PODNAME: Roadmap.pod

__END__

=pod

=encoding UTF-8

=head1 NAME

Roadmap.pod

=head1 VERSION

version 0.05

=head1 NAME

Roadmap.pod

=head1 VERSION

version 2019-05-01

=head1 ROADMAP

Here we set out the vision for the future of C<Proch::N50>.
B<0.0x> are alpha releases aiming to produce v. 0.1 as first stable release.
B<x.0> are major release, while B<x.y> are minor releases (y != 0).

=head1 v. 0.5

=over 4

=item *

Transition to FASTX::Reader that implements the same parser previously used here

=back

=head1 v. 1.0

=over 4

=item *

function getN50 tested on 100 datasets and compared with C<seqkit>.

=item *

updated n50.pl script in the scripts directory

=back

=head1 AUTHOR

Andrea Telatin <proch@cpan.org>

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2019 by Andrea Telatin.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=head1 AUTHOR

Andrea Telatin <andrea.telatin@quadram.ac.uk>

=head1 COPYRIGHT AND LICENSE

This software is Copyright (c) 2019 by Andrea Telatin.

This is free software, licensed under:

  The MIT (X11) License

=cut
